# Generated by Django 4.1 on 2022-08-15 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='movies.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='ages',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
